services:
    db:
        image: postgres:16.3
        volumes_from:
            - disk
        command: "postgres -c 'max_connections=500'"
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - "5433:5433"
    ruby:
        build:
            context: "./ruby"
            dockerfile: Dockerfile
            args:
                - SITE_EDITOR_GID=${SITE_EDITOR_GID}
                - DOCKER_USER_UID_GID=${DOCKER_USER_UID_GID}
                - DOCKER_WEB_USER=${DOCKER_WEB_USER}
                - RUBY_VERSION=${RUBY_VERSION}
        volumes_from:
            - disk
        environment:
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - "3000:3000"
        restart: "no"
        depends_on:
            - db
        tty: true
        stdin_open: true
    disk:
        image: ubuntu:24.04
        volumes:
            - ./web:/home/docker_user/web
            - ./db-data:/var/lib/postgresql/data
        # https://www.baeldung.com/ops/docker-compose-multiple-commands#1-using-the-ampamp-operator
        command: /bin/bash -c "chgrp ${SITE_EDITOR_GID} /home/docker_user/web; chmod 2775 /home/docker_user/web"
        restart: "no"